#!/usr/bin/env bash
# Prints the phrase indefinitely and handles SIGTERM by declaring invincibility

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
