#!/usr/bin/env bash
# This script prints "Best School" 10 times and "Hi" after the 9th time

i=1
while [ $i -le 10 ]
do
  echo "Best School"
  if [ $i -eq 9 ]; then
    echo "Hi"
  fi
  i=$((i + 1))
done
